Add Battery Spacing to the grid
googleinterns/step141-2020 pull request #39
Opened 2020-07-15 14:54 UTC by Lev-Stambler

- Have the grid automatically add batteries upon creation
- Space the batteries out among the grid by splitting it up into blocks
- Add get all positions to the grid state
- Add testing

2020-07-15 17:01 UTC, vitashubin requested changes

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts
> -    return this.currentBatteryPower;
can we rename this method to getCurrentBatteryEnergy
Usually getters and setters should be named get<variablename> and set<variablename>

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid-state/biogrid-state.spec.ts
> +    expect(totalEdges).toEqual(newVertices.length - 1);
nit: can you group the expect statements together and leave the logic above

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts
> +  private createBatteryPositions(
Don't you want small batteries to be specifically close to building positions? are buildings also spread throughout the town evenly or can they be at any location? If the latter, should battery positions take into account where the houses are?
Along with that, can you have a battery in the same position as a house?

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts
> +    const rows = numberOfBatteries / cols;
why is rows a float but cols uses Math.ceil?

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid.spec.ts
> +   * The small batteries are the x. THe larger are the *
nit: s/THe/The
Can we maybe represent batters using "s" and "L" or "x" and "y" to avoid representing larger batteries as a "*" since the *s in the leftmost column are part of the jsdoc comment and not of the graph

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid.spec.ts
> +      { x: 5, y: 9 },
I think this example use case might be too long to be an effective test. Might be more useful to have it a bit shorter so it's more human-readable

2020-07-15 17:01 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid.spec.ts
>    test('should ensure that the Biogrid take action works', () => {
nit: test naming consistency - either start all test names with "should" or avoid using should altogether. I recommend the latter and replacing "should" statement with action verbs and descriptive expectations (e.g. "biogrid takeaction updates state" > "should work")

2020-07-15 18:36 UTC, Lev-Stambler commented
Add TODO and link to github bug about smart placement algo

2020-07-15 19:22 UTC, Lev-Stambler commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts
> +    const rows = numberOfBatteries / cols;
Oh, it should theoretically be an int because cols divides numberOfBatteries. I will add a comment

2020-07-15 21:02 UTC, cwlarson-google approved these changes

2020-07-16 16:06 UTC, vitashubin approved these changes
Approved pending remaining comments. Looks great!

2020-07-16 16:06 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid.spec.ts
> +   * The small batteries are the s. THe larger are the L
nit: remove capital H in second "the"

2020-07-16 16:06 UTC, vitashubin commented on biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid.spec.ts
> +   * ------------
update chart to reflect new test case

2020-07-17 15:28 UTC, merged