Add weather api
googleinterns/step141-2020 pull request #61
Opened 2020-07-23 19:32 UTC by Lev-Stambler

- Add API for getting weather data
- Convert cloud percentage to power generated by solar panels
- Add data store for daily weather to decrease API usage
- Add tests
- Refactor to async / await to handle async call

2020-07-24 20:21 UTC, RolandNaijuka requested changes

2020-07-24 20:21 UTC, RolandNaijuka commented on biogrid/libs/weather/src/lib/weather.ts
> +export class WeatherLib {
How does this put into consideration the dates selected by the user? Can the api provide data about future dates?

2020-07-24 20:21 UTC, RolandNaijuka commented on biogrid/libs/weather/src/lib/weather.ts
> +    if (day.length < 2) day = '0' + day;
nit: use Template strings(es6 backticks) to concat the strings

2020-07-24 20:21 UTC, RolandNaijuka commented on biogrid/libs/weather/src/lib/weather.ts
> +      throw new Error('Date not found within the specified time range');
could you send the date as part of the Error
such as `` `${date} not found within the specified time range` ``
also clarify on the time range

2020-07-24 20:21 UTC, RolandNaijuka commented on biogrid/libs/weather/src/lib/weather.ts
> +    return this.weatherData[dateFormatted].cloudCoverage;
could you send the date as part of the Error
such as `` `${date} not found within the specified time range` ``
also clarify on the time range

2020-07-24 20:21 UTC, RolandNaijuka commented on biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts
> +    return 990 * (1 - 0.75 * Math.pow(cloudCoverage, 3)) / 1000;
nit: include these constants in the `bio-constants` file

2020-07-27 10:24 UTC, Lev-Stambler commented on biogrid/libs/weather/src/lib/weather.ts
> +export class WeatherLib {
The weather lib is just for the grid to use with whatever date it needs to specify

2020-07-27 18:03 UTC, RolandNaijuka requested changes

2020-07-27 18:03 UTC, RolandNaijuka commented on biogrid/libs/biogrid-simulator/src/lib/biobrain/biobrain-class.ts
> +    const allEnergyProviders = [...solarPanels];
I see you changed the filter solar panels but did not collect this part. can you insert the right variable which is the filtered solar panels

2020-07-27 18:04 UTC, RolandNaijuka commented on biogrid/libs/weather/src/lib/weather.ts
> +export class WeatherLib {
alright

2020-07-27 18:56 UTC, RolandNaijuka approved these changes

2020-07-27 19:44 UTC, merged